#!/bin/bash
# Script para visualizar a nova estrutura do projeto
# Use: bash view-structure.sh ou ./view-structure.sh

echo ""
echo "╔════════════════════════════════════════════════════════════════════╗"
echo "║                  ESTRUTURA DO PROJETO REORGANIZADO               ║"
echo "╚════════════════════════════════════════════════════════════════════╝"
echo ""

echo "📂 RAIZ DO PROJETO"
echo "├── 🔧 Configuração"
echo "│   ├── package.json              Dependências Node.js"
echo "│   ├── .env                      Variáveis de ambiente (gitignore)"
echo "│   ├── .env.example              Template de .env"
echo "│   ├── .gitignore                ✅ Novo - Proteção Git"
echo "│   └── README.md                 Este arquivo"
echo ""

echo "├── 🖥️ CÓDIGO"
echo "│   ├── 📂 public/                Frontend"
echo "│   │   ├── index.html            Página de login"
echo "│   │   └── dashboard.html        Dashboard protegido"
echo "│   │"
echo "│   └── 📂 src/                   Backend"
echo "│       ├── server.js             Servidor Express"
echo "│       ├── routes.js             Rotas da API"
echo "│       ├── database.js           SQLite"
echo "│       └── middleware.js         Autenticação JWT"
echo ""

echo "├── 📚 DOCUMENTAÇÃO"
echo "│   └── 📂 docs/                  ✅ Novo - Centralizado"
echo "│       ├── 📂 guides/            Guias e tutoriais"
echo "│       │   ├── START.md          ⭐ Comece aqui"
echo "│       │   ├── QUICKSTART.md     Primeiros passos"
echo "│       │   ├── README.md         Documentação completa"
echo "│       │   ├── INSTALLATION-WINDOWS.md"
echo "│       │   ├── DESAFIOS.md       15 desafios"
echo "│       │   ├── ARQUITETURA.md    Diagramas"
echo "│       │   ├── RESUMO.md         Resumo"
echo "│       │   ├── INDEX.md          Índice"
echo "│       │   ├── INVENTARIO.md     Lista de arquivos"
echo "│       │   └── README.md         ✅ Novo - Guia de leitura"
echo "│       │"
echo "│       └── 📂 api/               Referência de API"
echo "│           ├── API.md            Endpoints completos"
echo "│           └── README.md         ✅ Novo - Como usar API"
echo ""

echo "├── 🛠️ SCRIPTS"
echo "│   └── 📂 scripts/               ✅ Novo - Centralizado"
echo "│       ├── test-api.bat          Teste de API (Windows)"
echo "│       ├── install.sh            Instalação (Linux/Mac)"
echo "│       └── README.md             ✅ Novo - Como usar"
echo ""

echo "└── 📋 REFERÊNCIA"
echo "    ├── ESTRUTURA.md              ✅ Novo - Este mapa"
echo "    ├── REORGANIZACAO.md          ✅ Novo - Mudanças"
echo "    └── BOAS-VINDAS.txt           Mensagem de boas-vindas"
echo ""

echo "╔════════════════════════════════════════════════════════════════════╗"
echo "║                        O QUE MUDOU ✨                             ║"
echo "╚════════════════════════════════════════════════════════════════════╝"
echo ""

echo "✅ ADICIONADO"
echo "   • .gitignore                     Proteção Git"
echo "   • docs/                          Pasta de documentação"
echo "   • docs/guides/                   Guias"
echo "   • docs/api/                      API reference"
echo "   • scripts/                       Scripts"
echo "   • ESTRUTURA.md                   Mapa do projeto"
echo "   • REORGANIZACAO.md               Este arquivo"
echo ""

echo "✅ ORGANIZADO"
echo "   • Documentação centralizada em docs/"
echo "   • Scripts em scripts/"
echo "   • READMEs informativos em cada pasta"
echo ""

echo "✅ SEGURANÇA"
echo "   • .gitignore protege:"
echo "     - .env (credenciais)"
echo "     - node_modules/ (grande)"
echo "     - *.db (banco de dados)"
echo "     - *.log (logs)"
echo ""

echo "╔════════════════════════════════════════════════════════════════════╗"
echo "║                      PRÓXIMOS PASSOS                             ║"
echo "╚════════════════════════════════════════════════════════════════════╝"
echo ""

echo "1. Veja a nova estrutura:"
echo "   └─ cat ESTRUTURA.md"
echo ""

echo "2. Leia o guia de documentação:"
echo "   └─ cat docs/guides/README.md"
echo ""

echo "3. Comece a usar:"
echo "   └─ cat docs/guides/START.md"
echo ""

echo "4. Use controle de versão:"
echo "   └─ git add ."
echo "   └─ git commit -m 'Organizar estrutura do projeto'"
echo ""

echo "✅ Estrutura reorganizada com sucesso! 🎉"
echo ""
